### ISSUE TITLE
Docker installation doesn't work - error connecting to DB

### ISSUE THREAD

**Issue by keybits** [abhinavxd/libredesk#30]
Hi, thanks for creating this - it looks fantastic.

Following the Docker installation instructions, I did:

```
curl -LO https://github.com/abhinavxd/libredesk/raw/main/docker-compose.yml
curl -LO https://github.com/abhinavxd/libredesk/raw/main/config.sample.toml
cp config.sample.toml config.toml
docker-compose up -d
docker exec -it libredesk_app ./libredesk --set-system-user-password
```

The last command fails as the app container doesn't stay up and constantly restarts. In its log I see lots of:

```
2025/03/06 14:18:31 Build: v0.4.3-alpha (36d91de 2025-03-06T09:49:10Z, linux/arm64)
2025/03/06 14:18:31 Version: v0.4.3-alpha
2025/03/06 14:18:31 reading config file: /libredesk/config.toml
2025/03/06 14:18:31 error connecting to DB: dial tcp 127.0.0.1:5432: connect: connection refused
```

Connecting to the postgres container shows that the db exists but it has no tables.

```
4683edad8cd7:/# psql -U libredesk
psql (17.4)
Type "help" for help.

libredesk=# \c libredesk
You are now connected to database "libredesk" as user "libredesk".
libredesk=# \dt
Did not find any relations.
libredesk=#
```

Have I missed something or is this a bug with the Docker installation process?

**Comment by gianpaj** [comment]
@keybits you'll need to update 2 lines in the `config.toml` so the server can connect to Redis and Postgres

```toml
# Postgres.
[db]
# If using docker compose, use the service name as the host. e.g. db
host = "libredesk_db" # <--

#...

# Redis.
[redis]
# If using docker compose, use the service name as the host. e.g. redis:6379
address = "libredesk_redis:6379"  # <--
```
